version: '3'
services:
  grpc-server:
    build: .
    ports:
      - "50051:50051"

  envoy:
    image: envoyproxy/envoy:v1.22-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

